const ActionTypes = {
 SET_PRODUCTS: "SET_PRODUCTS",
 SELECTED_PRODUCT: "SELECTED_PRODUCT",
 CLEAR_SELECTED_PRODUCTS: "CLEAR_SELECTED_PRODUCTS",
 FAVOURITE_PRODUCTS: "FAVOURITE_PRODUCTS",
 TOGGLE_FAVORITE: "TOGGLE_FAVORITE",
 ADD_SELECTED_FAVOURITE_PRODUCT: "ADD_NEW_FAVOURITE_PRODUCT",
 REMOVE_SELECTED_FAVOURITE_PRODUCT: "ADD_NEW_FAVOURITE_PRODUCT",
 CART: "CART",
 RESET_STORE: "RESET_STORE",
};

export { ActionTypes };
